name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        cd api
        npm install
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
    
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
        # Créer également un lien symbolique dans /root/.ssh si nécessaire
        sudo mkdir -p /root/.ssh
        sudo cp ~/.ssh/id_rsa /root/.ssh/
        sudo chmod 600 /root/.ssh/id_rsa
        sudo cp ~/.ssh/known_hosts /root/.ssh/ || true
      
    - name: Update Ansible inventory
      run: |
        # Utiliser un chemin absolu et visible pour la clé SSH
        echo '[webservers]
        iot-sensors-vm ansible_host=${{ secrets.VM_HOST }} ansible_user=adminuser ansible_ssh_private_key_file=~/.ssh/id_rsa

        [all:vars]
        ansible_python_interpreter=/usr/bin/python3' > ansible/inventory.ini
    
    - name: Auto-commit all changes before deployment
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Auto-commit for deployment [skip ci]" || echo "No changes to commit"
    
    - name: Run deployment script
      run: |
        # Créer un script de déploiement simplifié pour CI
        cat > deploy-ci.sh << 'EOF'
        #!/bin/bash
        set -e
        echo "🔄 Déploiement avec Ansible..."
        ansible-playbook -i ansible/inventory.ini ansible/deploy.yml -vvv
        echo "✅ Déploiement terminé avec succès !"
        EOF
        chmod +x deploy-ci.sh
        ./deploy-ci.sh